### ISSUE TITLE
Allow language to be changed via XySubfilter tray context menu.

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#107]
Currently doesn't do anything, since subs can be changed now via the tray, why not audio too?

**Comment by zachsaw** [comment]
Because audio isn't in video graph... It's crazy XySubFilter even has anything to do with audio... heck that way why not create an audio renderer with a systray icon that allows you to select video and subtitle tracks too? It's bad design already to have a subtitle filter change audio track... Heck it shouldn't even change video track. Why stop at just changing audio tracks? Why not change audio delay, bitstream settings etc. too via the XySubFilter icon?

**Comment by Ryrynz** [comment]
LOL. Your call. Way I see it, if it's there why not make it work? Someone's bound to bring it up eventually.

**Comment by zachsaw** [comment]
Because it's impossible to make it work. The audio graph is separate in MPDN. When XySubFilter tries to change audio track, the request never gets passed to MPDN. Blame XySubFilter.

**Comment by Belphemur** [comment]
More I think about this, more I wonder if MPDN shouldn't set the reg key for XySubFilter to hide by default the systray.

Well there is no way to make it work if you use VSFilter as it should -> Only as a Subtitle Renderer.

**Comment by zachsaw** [comment]
LOL! That's true. :)
@Belphemur has some very interesting encounter with the shit design!

**Comment by zachsaw** [comment]
Hmm. I think I'll leave the systray icon as it is. Changing subtitles still work and really it should be all that it needs to do.
