### ISSUE TITLE
Error HRESULT E_FAIL when configuring Sanear audio renderer

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#108]
Access the options for Sanear via the Filters, info sent previously via PM.

**Comment by zachsaw** [comment]
Perhaps this should really be an issue for Sanear rather than MPDN or MPDN Extensions? The MPC Audio Renderer is open source, so I'm sure they'll figure out what their problem is.

**Comment by Ryrynz** [comment]
I can access it's options fine in BE using a similar method, are you sure it's related to Sanear? If so I'll raise it over there.

**Comment by zachsaw** [comment]
I'm not 100% sure but MPDN treats (and it shouldn't) all audio renderers the same. The same code is used for MPC Audio Renderer as it is for DirectSound Audio Renderer.

.NET is very strict when it comes to COM object conformance. For example, XySubFilter had a bug that prevented it to be used in .NET because it forgot to tell .NET it is an XySubFilter when it's queried. A common error that gets unnoticed in unmanaged code where you can cast it to anything and it'll never fail but .NET wants to make sure you can only cast it to something that is valid, for various reasons such as making sure you never have invalid access and above all security.

**Comment by zachsaw** [comment]
Wait a minute. I think that error message is actually correct - because Sanear simply returned E_FAIL when it is asked to display a property page... Do you see a Sanear specific config page when you tried it with MPC BE?

**Comment by Ryrynz** [comment]
Yeah the properties window loads which shows Status and Pin Info tabs.

**Comment by zachsaw** [comment]
Hmm... I'm not seeing the Status in GraphStudioNext...

**Comment by Ryrynz** [comment]
Guess that confirms it then.

**Comment by zachsaw** [comment]
Yeah I don't think it has a property page, otherwise its systray icon would probably have a menu item that allows you to bring it up. That said, I'll get MPDN to show a friendlier message when a filter returns E_FAIL when asked to display property page. It's the filter's fault though - it advertises that it has property pages to show but then when asked to show it, it simply returns E_FAIL!

**Comment by Ryrynz** [comment]
If you could make MPDN not freeze afterwards too that'd be grand ^-^

**Comment by zachsaw** [comment]
It doesn't freeze on my system... it just shows the error and if you dismiss it it'll continue to work fine.

**Comment by Ryrynz** [comment]
Yeah, no issues here now, I think I know what it was.. never mind.

**Comment by zachsaw** [comment]
I just checked Sanear's source code and found that it does implement property page but for some reason (didn't look further) it's not showing up in GraphStudioNext as well. So something's definitely wrong with their code.
