### ISSUE TITLE
Update MPDN and Extensions in one hit.

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#115]
If MPDN updates and breaks the currently installed extensions this kills the update functionality
preventing you from auto updating the extensions also. Download both packages together and
install to avoid the user having to download the extensions manually.

**Comment by Belphemur** [comment]
I was thinking of this too.

@zachsaw If the UpdateChecker is getting its own dll. Will that mean if the others extensions can't load (breakage in MPDN API by example), the UpdateChecker will still be loaded ?

**Comment by zachsaw** [comment]
No the DLL is still just another extension that needs the same extensions API. The only way would be like ryrynz said, to update both at the same time. 

Perhaps merging both of the updaters into just the one windrow would be best. I'll have a think about this a bit more.

**Comment by Belphemur** [comment]
It would be a mess to have only one window since you still have different version to download (like zip or installer, 64bit or 32bit). 

For now I advise to download the player update then close the window,  download the extension update, close the window. Install the extension then the player. This way I never had any problems. 

Would it be possible that MPDN load all compatible extension and disable the one that aren't working instead of disabling the whole package? 

After all,  it does know which one doesn't load since it gives an error message. It would just need to tell the user to update the extension because this one is not loading. And since the update checker is mostly a standalone it shouldn't be affected by API breakage. 

On 5 August 2015 00:41:14 EEST, Zach Saw <notifications@github.com> wrote:
>No the DLL is still just another extension that needs the same
>extensions API. The only way would be like ryrynz said, to update both
>at the same time. 
>
>Perhaps merging both of the updaters into just the one windrow would be
>best. I'll have a think about this a bit more. 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/issues/115#issuecomment-127770656

-- 
Best Regards, 
Antoine Aflalo

**Comment by zachsaw** [comment]
The breakage usually happens because the framework needs to be updated. This means almost all extensions will be affected.

**Comment by Belphemur** [comment]
Could the framework be divided into modules ?
Like a core one containing PlayerExtensions, Configuration a

**Comment by Belphemur** [comment]
Could the framework be divided into modules ?
Like a core one containing PlayerExtensions, Configuration, Exception and Helpers.
And another one containing the RenderScript, RenderChain and Scripting.

Because if I'm right there is less often change in the first package then in the second.

**Comment by Belphemur** [comment]
Other idea:

0. Make the UpdateChecker check for extensions first.
0. Set minimum MPDN version for Extensions in Extension installer.
0. Extensions installer check for which version is installed. [VersionCompare NSIS plugin](http://nsis.sourceforge.net/VersionCompare)
0. If the version doesn't match 
    * Net Download installer for MPDN (latest) for each version of MPDN installed
    * Run it (? in silent mode ?)
    * Continue installing extensions
0. If does match
    * Continue installing extensions

It would need some modification in the Make.bat to add an args for the Minimum MPDN version. But for the installer, it wouldn't be too many changes.

What do you think ?

**Comment by zachsaw** [comment]
I think ryrynz's request is mainly to do with convenience - i.e. whenever there's an update, regardless of whether it is the player or extensions, all the user needs to do is click "Install updates" and you're up to date.

The problem we face though is we have too many ways the user could've "installed" MPDN and its extensions. I think we should only target those who use installers only and leave the other classes of users with the existing method. It's a convenience feature anyway so we can assume those who use installers prefer convenience above all else.

The update checker could be modified to check and make sure MPDN and its extensions are installed via their respective installers. MPDN Extensions installer would need to be modified slightly to be given a command line parameter to update x86 or x64 only rather than both when both MPDN editions are installed. Whenever an update is available, whether it's the player or the extensions, the updater would display a message box to prompt the user to upgrade. This is the default "Simple" mode that doesn't show changelog or anything. It simply shows you an update is available and download it. If both the player and extensions need to be updated, this new simple mode downloader then downloads both and then run the installers in succession - via a batch file that runs in the background ([hidden](http://stackoverflow.com/questions/1096591/how-to-hide-cmd-window-while-running-a-batch-file) - make sure if user cancels out of the first installer, the second installer doesn't run). This batch file can be created on the fly and saved into user's temp folder.

**Comment by zachsaw** [comment]
For the non-installer users, we won't have to worry about them - we only download the zip files, they're in charge of the upgrading.

However for the last group of users - using MPDN installer but not the extensions, we can also improve update checker for them. Instead of running the installer right after MPDN's new version has been downloaded, wait until MPDN extensions have been checked for updates (and if available, downloaded) before bringing up file explorer to show the download location - and let the user run the installer(s) manually. 

Not too worried about this last group of users though since I doubt there's a lot of them and if there is, they're likely to know what they're doing anyway.

**Comment by Ryrynz** [comment]
What Zach said sounds good.

Would you care to have the extensions version number added on to MPDN's version number in the add/remove programs list? 2.39.1 / 1.12.1 for example.

**Comment by zachsaw** [comment]
Ah good idea. Create a new request.

**Comment by Belphemur** [comment]
In order:
0. Adding a simple mode in UpdateChecker. Checked by default.
0. this Simple mode show a dialog box with "Install Updates" or Cancel.
0. UpdateChecker download correct packages linked to the architecture of the launched player + Installer script (or generate it) (I'm thinking of doing a new installer for that that would launch the others installers in silent mode with the right arguments)
0. Launch installer script and close MPDN

This new Installer can then update also the registry with the version of Mpdn + Extensions. It can be create modulable, installing only player or extension or both.

This way the user whatever happen only see ONE installer that would install what is needed. Moreover It can use named parameter to it and it's code will be available on a github repository. (or here).

**Comment by zachsaw** [comment]
Some clarifications.

- [ ]  Add a simple mode in UpdateChecker. Checked by default only if both player and extensions are installed via an installer.
- [ ]  This Simple mode show a dialog box with "Install Updates" or Cancel.
- [ ]  UpdateChecker download correct packages linked to the architecture of the launched player
- [ ]  Create installer batch file in temp folder (make sure MPDN Extensions installer only install for the architecture of the launched player - it currently installs for both x86 and x64)
- [ ]  Launch batch file in hidden mode and close MPDN
- [ ]  Relaunch MPDN

**Comment by zachsaw** [comment]
I'm not sure I understand the last bit about having a new installer and it being modulable? If I understand what you're saying, wouldn't this require signing with a CA cert (otherwise you get an unknown publisher warning)?

That's the reason I wanted a batch file to run the existing installers in succession. It's cleaner that way and preserves all the certificates.

**Comment by Belphemur** [comment]
I was thinking of using an installer to not lose the user with double installer. (Since most of the time MPDN and the extension need to be updated in the same time.)

Are you sure that using MPDN to launch a generated batch script won't make the UAC trigger anyway ? (if I'm right the whole signing installer is to avoid this no ?)

**Comment by zachsaw** [comment]
It will trigger UAC - all installers will trigger UAC even when you've got it signed properly. The difference is those that aren't signed will be shown a warning that it's from an unknown publisher. Batch file will run just fine, but it'll just trigger UAC as it currently does when trying to run the installers. No difference there.

**Comment by Belphemur** [comment]
Okay I wasn't aware of the way the UAC works (since it's the first thing I always disable).

**Comment by zachsaw** [comment]
Ah I leave it enabled so I could test for it to see how it would affect the average user.

The one thing that I still can't workaround is the smartscreen filter that is enabled on the newer OSes by default. Without spending money to actually purchase a code signing cert, there's no way to stop it from saying MPDN installer is potentially a dangerous download!

**Comment by Belphemur** [comment]
I took the liberty of changing a little the checklist, in case only one installer is needed, no need of batch file, just do as before -> Donwload -> Run.

In case of both installer needed -> Batch file. 
Would you think it would be wise to put in this case the Extension Installer as silent ?

**Comment by zachsaw** [comment]
Actually I'd install the extensions first, then get the extensions installer to execwait MPDN installer as the final step. All we need to do is change the extensions installer to accept commandline params to run an external installer at the end of installation. We already need to modify it to accept commandline param to install for x86 / x64 only anyway. By default without any params, it functions as it currently does.

**Comment by Belphemur** [comment]
That what I was suggesting in the beginning of the thread. I'm completely for that idea. It could simply receive the name of the installer to run. 

In fact, the Extension Installer could in that case change its text, stating it's installing both and run the Player installer in silent mode (I know I'm annoying with the silent mode, but when updating ... why would I need to reaccept everything etc ... I just want the update done) then continue it's usual update way.

**Comment by zachsaw** [comment]
Oh I thought you meant new installer as in a separate installer to the existing extensions installer.
But I'm not sure the installer can be completely silent - does NSIS support it by default via some commandline params? If not it's no big deal. It's probably not a good idea to make it silent too as it takes quite a bit of time to install and the UI will not show any progress at all.

**Comment by Belphemur** [comment]
Yes NSIS have a silent mode, it's used by example by the installer when launching the uninstaller. It's a simple /S .
It does show the fact it run and wait for a program. (you can see it also in the installer of MPDN when launching the code optimizer)

**Comment by zachsaw** [comment]
Yeah it's very abstract for the average user though - ExecWait blah blah... that's why I chose to show a spinning loop window...

**Comment by zachsaw** [comment]
Let's just start without making it silent. We can always change that later anyway.

**Comment by Belphemur** [comment]
NSIS Provide a banner plugin (it's built-in in fact) to show a message that can be destroyed after it's not needed: http://nsis.sourceforge.net/Examples/Banner/Example.nsi

**Comment by zachsaw** [comment]
Oh... didn't know that! I might update MPDN installer to use it in the future.
